### ISSUE TITLE
agent_kwargs?

### ISSUE THREAD

**Issue by vrodriguezf** [ARCLab-MIT/kspdg#5]
I see that the AgentEnvRunner constructor has a `env_` argument to pass kwargs to the environment, but, how to do the same with Agents? I mean, this kwargs:
```python
class NaivePursuitAgent(KSPDGBaseAgent):
    """An agent that naively burns directly toward it's target"""
    def __init__(self, **kwargs):
        super().__init__()
```

In the config file `example_agent_cfg.yaml`  I see a way:
```
agent_module_path: "../src/kspdg/agent_api/example_agent.py"  # this must be relative to working directory when script is called
agent_cls: NaivePursuitAgent
kwargs:
  arg1: value1
  arg2: value2
  arg3: value3
```

but, afaik, that is supposed to be used only with the evaluation script.
